version: '3.3'
services:
  APP_NAME-MODE:
    image: theaska18/APP_NAME:MODE
    container_name: APP_NAME
    ports:
      - PORT:80
   # volumes:
    #  - ./app:/var/www/html
    networks:
      - cms-MODE
    restart: always
networks:
  cms-MODE:
    external: true